spring:
  datasource:
    data-username: root
    data-password: root
    driver-class-name: org.gjt.mm.mysql.Driver  #shujukuxinxi
    url: jdbc:mysql://localost:3306/pepsy?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
