spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver  #shujukuxinxi
    url: jdbc:mysql://localhost:3306/pepsy?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: http://192.168.22.131
    port: 15672
